export const GET_DEVELOPERS_REQUEST = 'GET_DEVELOPERS_REQUEST';
export const GET_DEVELOPERS_SUCCESS = 'GET_DEVELOPERS_SUCCESS';
export const GET_DEVELOPERS_FAIL = 'GET_DEVELOPERS_FAIL';
export const ADD_DEVELOPER = 'ADD_DEVELOPER';
